export const PURPLE = "#a855f7";

export const U = {
  shell: {
    minHeight: "100vh",
    background: "#000000",
    color: "#fff",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif",
  },
  inner: {
    maxWidth: 720,
    margin: "0 auto",
    padding: "0 20px 40px",
    boxSizing: "border-box",
  },
  card: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 12,
    padding: 20,
  },
  cardMuted: {
    background: "#111",
    border: "1px solid #2a2a2a",
    borderRadius: 12,
    padding: 16,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: "#ffffff",
    margin: "0 0 8px",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#ffffff",
    margin: "0 0 12px",
  },
  muted: { color: "#6b7280", fontSize: 13, lineHeight: 1.5 },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#9ca3af",
    textTransform: "uppercase",
    letterSpacing: ".5px",
    marginBottom: 6,
  },
  select: (disabled) => ({
    width: "100%",
    maxWidth: 400,
    boxSizing: "border-box",
    background: "#0d0d0d",
    border: `1px solid ${disabled ? "#1f1f1f" : "#2a2a2a"}`,
    borderRadius: 8,
    padding: "10px 13px",
    color: disabled ? "#6b7280" : "#e5e7eb",
    fontFamily: "inherit",
    fontSize: 14,
    outline: "none",
    marginTop: 8,
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  btnPrimary: {
    background: PURPLE,
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 20px",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    transition: "opacity .15s",
  },
  btnPrimaryDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  btnGhost: {
    background: "transparent",
    color: "#9ca3af",
    border: "1px solid #2a2a2a",
    borderRadius: 8,
    padding: "10px 18px",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnDanger: {
    background: "transparent",
    color: "#ef4444",
    border: "1px solid #ef444433",
    borderRadius: 8,
    padding: "10px 18px",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 12,
    padding: "16px 10px",
    textAlign: "center",
  },
};
